spring:
#  spring 캐시를 redis를 통해 사용
  cache:
    type: redis
#  session: storage-type = 기본 세션에 저장하는 값을 redis에 저장하겠다는 의미
  session:
    storage-type: redis

  data:
    redis:
      host: localhost
      port: 6379

